name: static-tests
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@1.1.0
      #    env:
      #  SHELLCHECK_OPTS: -e SC1091,SC1117,SC2001
  shfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shfmt
      uses: bltavares/actions/shfmt@master
      env:
        SHFMT_ARGS: -d -i 2
